const FETCH_ALL_TOPICS_START = 'FETCH_ALL_TOPICS_START';
const FETCH_ALL_TOPICS_SUCCESS = 'FETCH_ALL_TOPICS_SUCCESS';
const FETCH_ALL_TOPICS_FAIL = 'FETCH_ALL_TOPICS_FAIL';

export {
  FETCH_ALL_TOPICS_FAIL, FETCH_ALL_TOPICS_START, FETCH_ALL_TOPICS_SUCCESS,
};
