const ASSIGN_GOAL = 'ASSIGN_GOAL';
const ASSIGN_TEAM_GOAL = 'ASSIGN_TEAM_GOAL';
const ASSIGN_PERSONAL_GOAL = 'ASSIGN_PERSONAL_GOAL';

const REMOVE_GOAL = 'REMOVE_GOAL';
const REMOVE_PERSONAL_GOAL = 'REMOVE_PERSONAL_GOAL';

const SAVE_GOALS_START = 'SAVE_GOALS_START';
const SAVE_GOALS_SUCCESS = 'SAVE_GOALS_SUCCESS';
const SAVE_GOALS_FAIL = 'SAVE_GOALS_FAIL';

const RESET_GOALS = 'RESET_GOALS';

export {
  ASSIGN_GOAL, ASSIGN_TEAM_GOAL, ASSIGN_PERSONAL_GOAL, REMOVE_GOAL, REMOVE_PERSONAL_GOAL, SAVE_GOALS_START, SAVE_GOALS_SUCCESS, SAVE_GOALS_FAIL, RESET_GOALS,
};
