const LOGIN_START = 'LOGIN_START';
const LOGOUT = 'LOGOUT';
const FETCH_SELF_START = 'FETCH_SELF_START';

const FETCH_SELF_SUCCESS = 'FETCH_SELF_SUCCESS';
const FETCH_SELF_FAIL = 'FETCH_SELF_FAIL';

const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAIL = 'LOGIN_FAIL';

export {
  LOGIN_START, FETCH_SELF_START, FETCH_SELF_SUCCESS, FETCH_SELF_FAIL, LOGIN_SUCCESS, LOGIN_FAIL, LOGOUT,
};
