const LOGIN_START = 'LOGIN_START';
const LOGOUT = 'LOGOUT';
const REGISTER_START = 'REGISTER_START';
const FETCH_SELF_START = 'FETCH_SELF_START';

const FETCH_SELF_SUCCESS = 'FETCH_SELF_SUCCESS';
const FETCH_SELF_FAIL = 'FETCH_SELF_FAIL';

const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAIL = 'LOGIN_FAIL';

const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAIL = 'REGISTER_FAIL';

const INVITE_START = 'INVITE_START';
const INVITE_SUCCESS = 'INVITE_SUCCESS';
const INVITE_FAIL = 'INVITE_FAIL';

export {
  LOGIN_START, REGISTER_START, FETCH_SELF_START, FETCH_SELF_SUCCESS, FETCH_SELF_FAIL, LOGIN_SUCCESS, LOGIN_FAIL, REGISTER_SUCCESS, REGISTER_FAIL, LOGOUT, INVITE_FAIL, INVITE_START, INVITE_SUCCESS,
};
