const EDIT_TOPIC_START = 'EDIT_TOPIC_START';
const EDIT_TOPIC_SUCCESS = 'EDIT_TOPIC_SUCCESS';
const EDIT_TOPIC_FAIL = 'EDIT_TOPIC_FAIL';
const SUSPEND_EDIT_TOPIC = 'SUSPEND_EDIT_TOPIC';

export {
  EDIT_TOPIC_START, EDIT_TOPIC_SUCCESS, EDIT_TOPIC_FAIL, SUSPEND_EDIT_TOPIC,
};
