const EDIT_LIMIT_START = 'EDIT_LIMIT_START';
const EDIT_LIMIT_SUCCESS = 'EDIT_LIMIT_SUCCESS';
const EDIT_LIMIT_FAIL = 'EDIT_LIMIT_FAIL';
const SUSPEND_EDIT_LIMIT = 'SUSPEND_EDIT_LIMIT';

export {
  EDIT_LIMIT_START, EDIT_LIMIT_SUCCESS, EDIT_LIMIT_FAIL, SUSPEND_EDIT_LIMIT,
};
