const FETCH_GLOBAL_LIMITS_START = 'FETCH_GLOBAL_LIMITS_START';
const FETCH_GLOBAL_LIMITS_SUCCESS = 'FETCH_GLOBAL_LIMITS_SUCCESS';
const FETCH_GLOBAL_LIMITS_FAIL = 'FETCH_GLOBAL_LIMITS_FAIL';

const SAVE_GLOBAL_LIMITS_START = 'SAVE_GLOBAL_LIMITS_START';
const SAVE_GLOBAL_LIMITS_SUCCESS = 'SAVE_GLOBAL_LIMITS_SUCCESS';
const SAVE_GLOBAL_LIMITS_FAIL = 'SAVE_GLOBAL_LIMITS_FAIL';

export {
  FETCH_GLOBAL_LIMITS_START, FETCH_GLOBAL_LIMITS_SUCCESS, FETCH_GLOBAL_LIMITS_FAIL,
  SAVE_GLOBAL_LIMITS_START, SAVE_GLOBAL_LIMITS_SUCCESS, SAVE_GLOBAL_LIMITS_FAIL,
};
