const INVITE_START = 'INVITE_START';
const INVITE_SUCCESS = 'INVITE_SUCCESS';
const INVITE_FAIL = 'INVITE_FAIL';
const INVITE_SUSPEND = 'INVITE_SUSPEND';

export {
  INVITE_START, INVITE_SUCCESS, INVITE_FAIL, INVITE_SUSPEND,
};
