const FETCH_LEARNING_DAYS_START = 'FETCH_LEARNING_DAYS_START';
const FETCH_LEARNING_DAYS_SUCCESS = 'FETCH_LEARNING_DAYS_SUCCESS';
const FETCH_LEARNING_DAYS_FAIL = 'FETCH_LEARNING_DAYS_FAIL';

export {
  FETCH_LEARNING_DAYS_START, FETCH_LEARNING_DAYS_SUCCESS, FETCH_LEARNING_DAYS_FAIL,
};
