const FETCH_LEARNING_DAYS_START = 'FETCH_LEARNING_DAYS_START';
const FETCH_LEARNING_DAYS_SUCCESS = 'FETCH_LEARNING_DAYS_SUCCESS';
const FETCH_LEARNING_DAYS_FAIL = 'FETCH_LEARNING_DAYS_FAIL';

const START_LEARNING_DAY_START = 'START_LEARNING_DAY_START';
const START_LEARNING_DAY_SUCCESS = 'START_LEARNING_DAY_SUCCESS';
const START_LEARNING_DAY_FAIL = 'START_LEARNING_DAY_FAIL';
const START_LEARNING_DAY_SUSPEND = 'START_LEARNING_DAY_SUSPEND';

const CANCEL_LEARNING_DAY_START = 'CANCEL_LEARNING_DAY_START';
const CANCEL_LEARNING_DAY_SUCCESS = 'CANCEL_LEARNING_DAY_SUCCESS';
const CANCEL_LEARNING_DAY_FAIL = 'CANCEL_LEARNING_DAY_FAIL';
const CANCEL_LEARNING_DAY_SUSPEND = 'CANCEL_LEARNING_DAY_SUSPEND';

export {
  FETCH_LEARNING_DAYS_START, FETCH_LEARNING_DAYS_SUCCESS, FETCH_LEARNING_DAYS_FAIL,
  START_LEARNING_DAY_FAIL, START_LEARNING_DAY_START, START_LEARNING_DAY_SUCCESS,
  START_LEARNING_DAY_SUSPEND, CANCEL_LEARNING_DAY_START, CANCEL_LEARNING_DAY_FAIL, CANCEL_LEARNING_DAY_SUCCESS, CANCEL_LEARNING_DAY_SUSPEND,
};
