const FETCH_LIMITS_START = 'FETCH_LIMITS_START';
const FETCH_LIMITS_SUCCESS = 'FETCH_LIMITS_SUCCESS';
const FETCH_LIMITS_FAIL = 'FETCH_LIMITS_FAIL';

export {
  FETCH_LIMITS_START, FETCH_LIMITS_SUCCESS, FETCH_LIMITS_FAIL,
};
