const FETCH_MY_SUBORDINATES_TREE_START = 'FETCH_MY_SUBORDINATES_TREE_START';
const FETCH_MY_SUBORDINATES_TREE_SUCCESS = 'FETCH_MY_SUBORDINATES_TREE_SUCCESS';
const FETCH_MY_SUBORDINATES_TREE_FAIL = 'FETCH_MY_SUBORDINATES_TREE_FAIL';
const SUSPEND_MY_SUBORDINATES_TREE = 'SUSPEND_MY_SUBORDINATES_TREE';

export {
  FETCH_MY_SUBORDINATES_TREE_START, FETCH_MY_SUBORDINATES_TREE_SUCCESS, FETCH_MY_SUBORDINATES_TREE_FAIL, SUSPEND_MY_SUBORDINATES_TREE,
};
