const FETCH_MY_TEAM_TREE_START = 'FETCH_MY_TEAM_TREE_START';
const FETCH_MY_TEAM_TREE_SUCCESS = 'FETCH_MY_TEAM_TREE_SUCCESS';
const FETCH_MY_TEAM_TREE_FAIL = 'FETCH_MY_TEAM_TREE_FAIL';

export {
  FETCH_MY_TEAM_TREE_START, FETCH_MY_TEAM_TREE_SUCCESS, FETCH_MY_TEAM_TREE_FAIL,
};
