const FETCH_MY_TEAM_START = 'FETCH_MY_TEAM_START';
const FETCH_MY_TEAM_SUCCESS = 'FETCH_MY_TEAM_SUCCESS';
const FETCH_MY_TEAM_FAIL = 'FETCH_MY_TEAM_FAIL';

export {
  FETCH_MY_TEAM_START, FETCH_MY_TEAM_SUCCESS, FETCH_MY_TEAM_FAIL,
};
