const FETCH_PERSONAL_TREE_START = 'FETCH_PERSONAL_TREE_START';
const FETCH_PERSONAL_TREE_SUCCESS = 'FETCH_PERSONAL_TREE_SUCCESS';
const FETCH_PERSONAL_TREE_FAIL = 'FETCH_PERSONAL_TREE_FAIL';

export {
  FETCH_PERSONAL_TREE_START, FETCH_PERSONAL_TREE_SUCCESS, FETCH_PERSONAL_TREE_FAIL,
};
