const FETCH_PERSONAL_TREE_START = 'FETCH_PERSONAL_TREE_START';
const FETCH_PERSONAL_TREE_SUCCESS = 'FETCH_PERSONAL_TREE_SUCCESS';
const FETCH_PERSONAL_TREE_FAIL = 'FETCH_PERSONAL_TREE_FAIL';
const SUSPEND_PERSONAL_TREE = 'SUSPEND_PERSONAL_TREE';

export {
  FETCH_PERSONAL_TREE_START, FETCH_PERSONAL_TREE_SUCCESS, FETCH_PERSONAL_TREE_FAIL, SUSPEND_PERSONAL_TREE,
};
