const FETCH_PERSONAL_GOALS_START = 'FETCH_PERSONAL_GOALS_START';
const FETCH_PERSONAL_GOALS_SUCCESS = 'FETCH_PERSONAL_GOALS_SUCCESS';
const FETCH_PERSONAL_GOALS_FAIL = 'FETCH_PERSONAL_GOALS_FAIL';

const ADD_SELF_PERSONAL_GOAL_START = 'ADD_SELF_PERSONAL_GOAL_START';
const ADD_SELF_PERSONAL_GOAL_SUCCESS = 'ADD_SELF_PERSONAL_GOAL_SUCCESS';
const ADD_SELF_PERSONAL_GOAL_FAIL = 'ADD_SELF_PERSONAL_GOAL_FAIL';
const SUSPEND_ADD_SELF_PERSONAL_GOAL = 'SUSPEND_ADD_SELF_PERSONAL_GOAL';

const MARK_GOAL_LEARNED_START = 'MARK_GOAL_LEARNED_START';
const MARK_GOAL_LEARNED_SUCCESS = 'MARK_GOAL_LEARNED_SUCCESS';
const MARK_GOAL_LEARNED_FAIL = 'MARK_GOAL_LEARNED_FAIL';
const SUSPEND_MARK_GOAL_LEARNED = 'SUSPEND_MARK_GOAL_LEARNED';

export {
  FETCH_PERSONAL_GOALS_START, FETCH_PERSONAL_GOALS_SUCCESS, FETCH_PERSONAL_GOALS_FAIL,
  ADD_SELF_PERSONAL_GOAL_FAIL, ADD_SELF_PERSONAL_GOAL_START, ADD_SELF_PERSONAL_GOAL_SUCCESS,
  SUSPEND_ADD_SELF_PERSONAL_GOAL, MARK_GOAL_LEARNED_FAIL, MARK_GOAL_LEARNED_START, MARK_GOAL_LEARNED_SUCCESS,
  SUSPEND_MARK_GOAL_LEARNED,
};
