const FETCH_PERSONAL_GOALS_START = 'FETCH_PERSONAL_GOALS_START';
const FETCH_PERSONAL_GOALS_SUCCESS = 'FETCH_PERSONAL_GOALS_SUCCESS';
const FETCH_PERSONAL_GOALS_FAIL = 'FETCH_PERSONAL_GOALS_FAIL';

const ADD_SELF_PERSONAL_GOAL_START = 'ADD_SELF_PERSONAL_GOAL_START';
const ADD_SELF_PERSONAL_GOAL_SUCCESS = 'ADD_SELF_PERSONAL_GOAL_SUCCESS';
const ADD_SELF_PERSONAL_GOAL_FAIL = 'ADD_SELF_PERSONAL_GOAL_FAIL';
const SUSPEND_ADD_SELF_PERSONAL_GOAL = 'SUSPEND_ADD_SELF_PERSONAL_GOAL';

export {
  FETCH_PERSONAL_GOALS_START, FETCH_PERSONAL_GOALS_SUCCESS, FETCH_PERSONAL_GOALS_FAIL,
  ADD_SELF_PERSONAL_GOAL_FAIL, ADD_SELF_PERSONAL_GOAL_START, ADD_SELF_PERSONAL_GOAL_SUCCESS,
  SUSPEND_ADD_SELF_PERSONAL_GOAL,
};
