const FETCH_PERSONAL_GOALS_START = 'FETCH_PERSONAL_GOALS_START';
const FETCH_PERSONAL_GOALS_SUCCESS = 'FETCH_PERSONAL_GOALS_SUCCESS';
const FETCH_PERSONAL_GOALS_FAIL = 'FETCH_PERSONAL_GOALS_FAIL';

export {
  FETCH_PERSONAL_GOALS_START, FETCH_PERSONAL_GOALS_SUCCESS, FETCH_PERSONAL_GOALS_FAIL,
};
