const VALIDATE_INVITEID_START = 'VALIDATE_INVITEID_START';
const VALIDATE_INVITEID_SUCCESS = 'VALIDATE_INVITEID_SUCCESS';
const VALIDATE_INVITEID_FAIL = 'VALIDATE_INVITEID_FAIL';

const REGISTER_START = 'REGISTER_START';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAIL = 'REGISTER_FAIL';

export {
  REGISTER_START, REGISTER_SUCCESS, REGISTER_FAIL, VALIDATE_INVITEID_START, VALIDATE_INVITEID_SUCCESS, VALIDATE_INVITEID_FAIL,
};
