const FETCH_SINGLE_TEAM_TREE_START = 'FETCH_SINGLE_TEAM_TREE_START';
const FETCH_SINGLE_TEAM_TREE_SUCCESS = 'FETCH_SINGLE_TEAM_TREE_SUCCESS';
const FETCH_SINGLE_TEAM_TREE_FAIL = 'FETCH_SINGLE_TEAM_TREE_FAIL';
const SUSPEND_SINGLE_TEAM_TREE = 'SUSPEND_SINGLE_TEAM_TREE';

export {
  FETCH_SINGLE_TEAM_TREE_START, FETCH_SINGLE_TEAM_TREE_SUCCESS, FETCH_SINGLE_TEAM_TREE_FAIL, SUSPEND_SINGLE_TEAM_TREE,
};
