const FETCH_SUBORDINATES_START = 'FETCH_SUBORDINATES_START';
const FETCH_SUBORDINATES_SUCCESS = 'FETCH_SUBORDINATES_SUCCESS';
const FETCH_SUBORDINATES_FAIL = 'FETCH_SUBORDINATES_FAIL';

export {
  FETCH_SUBORDINATES_START, FETCH_SUBORDINATES_SUCCESS, FETCH_SUBORDINATES_FAIL,
};
