const FETCH_SUBORDINATES_START = 'FETCH_SUBORDINATES_START';
const FETCH_SUBORDINATES_SUCCESS = 'FETCH_SUBORDINATES_SUCCESS';
const FETCH_SUBORDINATES_FAIL = 'FETCH_SUBORDINATES_FAIL';

const UPDATE_SUBORDINATE_START = 'UPDATE_SUBORDINATE_START';
const UPDATE_SUBORDINATE_SUCCESS = 'UPDATE_SUBORDINATE_SUCCESS';
const UPDATE_SUBORDINATE_FAIL = 'UPDATE_SUBORDINATE_FAIL';
const UPDATE_SUBORDINATE_SUSPEND = 'UPDATE_SUBORDINATE_SUSPEND';

const DELETE_SUBORDINATE_START = 'DELETE_SUBORDINATE_START';
const DELETE_SUBORDINATE_SUCCESS = 'DELETE_SUBORDINATE_SUCCESS';
const DELETE_SUBORDINATE_FAIL = 'DELETE_SUBORDINATE_FAIL';
const DELETE_SUBORDINATE_SUSPEND = 'DELETE_SUBORDINATE_SUSPEND';

export {
  FETCH_SUBORDINATES_START, FETCH_SUBORDINATES_SUCCESS, FETCH_SUBORDINATES_FAIL,
  UPDATE_SUBORDINATE_START, UPDATE_SUBORDINATE_SUCCESS, UPDATE_SUBORDINATE_FAIL, UPDATE_SUBORDINATE_SUSPEND,
  DELETE_SUBORDINATE_START, DELETE_SUBORDINATE_SUCCESS, DELETE_SUBORDINATE_FAIL, DELETE_SUBORDINATE_SUSPEND,
};
