const SHOW_SUCCESS_TOAST = 'SHOW_SUCCESS_TOAST';
const HIDE_SUCCESS_TOAST = 'HIDE_SUCCESS_TOAST';

const SHOW_ERROR_TOAST = 'SHOW_ERROR_TOAST';
const HIDE_ERROR_TOAST = 'HIDE_ERROR_TOAST';

const SHOW_WARNING_TOAST = 'SHOW_WARNING_TOAST';
const HIDE_WARNING_TOAST = 'HIDE_WARNING_TOAST';

export {
  SHOW_SUCCESS_TOAST, HIDE_SUCCESS_TOAST, SHOW_ERROR_TOAST, HIDE_ERROR_TOAST, SHOW_WARNING_TOAST, HIDE_WARNING_TOAST,
};
