const SHOW_SUCCESS_TOAST = 'SHOW_SUCCESS_TOAST';
const HIDE_SUCCESS_TOAST = 'HIDE_SUCCESS_TOAST';

const SHOW_ERROR_TOAST = 'SHOW_ERROR_TOAST';
const HIDE_ERROR_TOAST = 'HIDE_ERROR_TOAST';

export {
  SHOW_SUCCESS_TOAST, HIDE_SUCCESS_TOAST, SHOW_ERROR_TOAST, HIDE_ERROR_TOAST,
};
