const CREATE_TOPIC_START = 'CREATE_TOPIC_START';
const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
const CREATE_TOPIC_FAIL = 'CREATE_TOPIC_FAIL';
const SUSPEND_CREATE_TOPIC = 'SUSPEND_CREATE_TOPIC';

export {
  CREATE_TOPIC_FAIL, CREATE_TOPIC_START, CREATE_TOPIC_SUCCESS, SUSPEND_CREATE_TOPIC,
};
