const CREATE_TOPIC_START = 'CREATE_TOPIC_START';
const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
const CREATE_TOPIC_FAIL = 'CREATE_TOPIC_FAIL';
const SUSPEND_CREATE_TOPIC = 'SUSPEND_CREATE_TOPIC';

const FETCH_TOPIC_START = 'FETCH_TOPIC_START';
const FETCH_TOPIC_FAIL = 'FETCH_TOPIC_FAIL';
const FETCH_TOPIC_SUCCESS = 'FETCH_TOPIC_SUCCESS';

export {
  CREATE_TOPIC_FAIL, CREATE_TOPIC_START, CREATE_TOPIC_SUCCESS, SUSPEND_CREATE_TOPIC, FETCH_TOPIC_FAIL, FETCH_TOPIC_START, FETCH_TOPIC_SUCCESS,
};
