const CREATE_TOPIC_START = 'CREATE_TOPIC_START';
const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
const CREATE_TOPIC_FAIL = 'CREATE_TOPIC_FAIL';
const SUSPEND_CREATE_TOPIC = 'SUSPEND_CREATE_TOPIC';

const FETCH_TOPIC_START = 'FETCH_TOPIC_START';
const FETCH_TOPIC_FAIL = 'FETCH_TOPIC_FAIL';
const FETCH_TOPIC_SUCCESS = 'FETCH_TOPIC_SUCCESS';

const FETCH_LEARNED_TOPICS_START = 'FETCH_LEARNED_TOPICS_START';
const FETCH_LEARNED_TOPICS_FAIL = 'FETCH_LEARNED_TOPICS_FAIL';
const FETCH_LEARNED_TOPICS_SUCCESS = 'FETCH_LEARNED_TOPICS_SUCCESS';
const SUSPEND_FETCH_LEARNED_TOPICS = 'SUSPEND_FETCHED_LEARNED_TOPICS';

export {
  CREATE_TOPIC_FAIL, CREATE_TOPIC_START, CREATE_TOPIC_SUCCESS, SUSPEND_CREATE_TOPIC, FETCH_TOPIC_FAIL, FETCH_TOPIC_START, FETCH_TOPIC_SUCCESS,
  FETCH_LEARNED_TOPICS_SUCCESS, FETCH_LEARNED_TOPICS_START, FETCH_LEARNED_TOPICS_FAIL, SUSPEND_FETCH_LEARNED_TOPICS,
};
