const FETCH_TOPICS_START = 'FETCH_TOPICS_START';
const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
const FETCH_TOPICS_FAIL = 'FETCH_TOPICS_FAIL';

export {
  FETCH_TOPICS_START, FETCH_TOPICS_SUCCESS, FETCH_TOPICS_FAIL,
};
