const FETCH_TOPICS_TREE_START = 'FETCH_TOPICS_TREE_START';
const FETCH_TOPICS_TREE_SUCCESS = 'FETCH_TOPICS_TREE_SUCCESS';
const FETCH_TOPICS_TREE_FAIL = 'FETCH_TOPICS_TREE_FAIL';

export {
  FETCH_TOPICS_TREE_FAIL, FETCH_TOPICS_TREE_START, FETCH_TOPICS_TREE_SUCCESS,
};
