const LOADING_ALL_TOPICS = 'LOADING_ALL_TOPICS';
const FETCH_ALL_TOPICS_FAILED = 'FETCH_ALL_TOPICS_FAILED';
const FETCH_ALL_TOPICS_SUCCEEDED = 'FETCH_ALL_TOPICS_SUCCEEDED';

export {
  LOADING_ALL_TOPICS, FETCH_ALL_TOPICS_FAILED, FETCH_ALL_TOPICS_SUCCEEDED,
};
