const SAVING_GOALS = 'SAVING_GOALS';
const SAVE_GOALS_SUCCEEDED = 'SAVE_GOALS_SUCCEEDED';
const SAVE_GOALS_FAILED = 'SAVE_GOALS_FAILED';
const SAVE_GOALS_INACTIVE = 'SAVE_GOALS_INACTIVE';

export {
  SAVING_GOALS, SAVE_GOALS_SUCCEEDED, SAVE_GOALS_FAILED, SAVE_GOALS_INACTIVE,
};
