const NO_NEW_GOALS = 'NO_NEW_GOALS';
const NEW_GOALS_ADDED = 'NEW_GOALS_ADDED';

const SAVING_GOALS = 'SAVING_GOALS';
const SAVE_GOALS_SUCCEEDED = 'SAVE_GOALS_SUCCEEDED';
const SAVE_GOALS_FAILED = 'SAVE_GOALS_FAILED';

export {
  NO_NEW_GOALS, NEW_GOALS_ADDED, SAVING_GOALS, SAVE_GOALS_SUCCEEDED, SAVE_GOALS_FAILED,
};
