const LOGGED_IN = 'LOGGED_IN';
const LOGGED_OUT = 'LOGGED_OUT';

const LOADING_FETCH_SELF = 'LOADING_FETCH_SELF';
const LOADING_LOGIN = 'LOADING_LOGIN';

const LOGIN_FAILED = 'LOGIN_FAILED';

const FETCH_SELF_FAILED = 'FETCH_SELF_FAILED';

export {
  LOGGED_IN, LOGGED_OUT, LOADING_FETCH_SELF, LOADING_LOGIN, FETCH_SELF_FAILED, LOGIN_FAILED,
};
