const LOGGED_IN = 'LOGGED_IN';
const LOGGED_OUT = 'LOGGED_OUT';

const LOADING_FETCH_SELF = 'LOADING_FETCH_SELF';
const LOADING_LOGIN = 'LOADING_LOGIN';
const LOADING_REGISTER = 'LOADING_REGISTER';

const LOGIN_FAILED = 'LOGIN_FAIL';

const FETCH_SELF_FAILED = 'FETCH_SELF_FAILED';

const REGISTER_FAILED = 'REGISTER_FAIL';
const REGISTER_SUCCEEDED = 'REGISTER_SUCCEEDED';

export {
  LOGGED_IN, LOGGED_OUT, LOADING_FETCH_SELF, LOADING_LOGIN, LOADING_REGISTER, FETCH_SELF_FAILED, LOGIN_FAILED, REGISTER_FAILED, REGISTER_SUCCEEDED,
};
