const LOADING_CHANGE_PASSWORD = 'LOADING_CHANGE_PASSWORD';
const CHANGE_FAILED_PASSWORD = 'CHANGE_FAILED_PASSWORD';
const CHANGE_SUCCEEDED_PASSWORD = 'CHANGE_SUCCEEDED_PASSWORD';

export {
  LOADING_CHANGE_PASSWORD, CHANGE_FAILED_PASSWORD, CHANGE_SUCCEEDED_PASSWORD,
};
