const LOADING_CHANGE_PASSWORD = 'LOADING_CHANGE_PASSWORD';
const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';
const CHANGE_PASSWORD_SUCCEEDED = 'CHANGE_PASSWORD_SUCCEEDED';

export {
  LOADING_CHANGE_PASSWORD, CHANGE_PASSWORD_FAILED, CHANGE_PASSWORD_SUCCEEDED,
};
