const LOADING_EDIT_TOPIC = 'LOADING_EDIT_TOPIC';
const EDIT_TOPIC_FAILED = 'EDIT_TOPIC_FAILED';
const EDIT_TOPIC_SUCCEEDED = 'EDIT_TOPIC_SUCCEEDED';
const EDIT_TOPIC_INACTIVE = 'EDIT_TOPIC_INACTIVE';

export {
  LOADING_EDIT_TOPIC, EDIT_TOPIC_FAILED, EDIT_TOPIC_SUCCEEDED, EDIT_TOPIC_INACTIVE,
};
