const LOADING_EDIT_LIMIT = 'LOADING_EDIT_LIMIT';
const EDIT_LIMIT_FAILED = 'EDIT_LIMIT_FAILED';
const EDIT_LIMIT_SUCCEEDED = 'EDIT_LIMIT_SUCCEEDED';
const EDIT_LIMIT_INACTIVE = 'EDIT_LIMIT_INACTIVE';

export {
  LOADING_EDIT_LIMIT, EDIT_LIMIT_FAILED, EDIT_LIMIT_SUCCEEDED, EDIT_LIMIT_INACTIVE,
};
