const LOADING_FETCH_TOPICS = 'LOADING_FETCH_TOPICS';
const FETCH_TOPICS_SUCCEEDED = 'FETCH_TOPICS_SUCCEEDED';
const FETCH_TOPICS_FAILED = 'FETCH_TOPICS_FAILED';

export {
  LOADING_FETCH_TOPICS, FETCH_TOPICS_SUCCEEDED, FETCH_TOPICS_FAILED,
};
