const INACTIVE_FETCH_GLOBAL_LIMITS = 'INACTIVE_FETCH_GLOBAL_LIMITS';
const LOADING_FETCH_GLOBAL_LIMITS = 'LOADING_FETCH_GLOBAL_LIMITS';
const FETCH_GLOBAL_LIMITS_SUCCEEDED = 'FETCH_GLOBAL_LIMITS_SUCCEEDED';
const FETCH_GLOBAL_LIMITS_FAILED = 'FETCH_GLOBAL_LIMITS_FAILED';

const INACTIVE_SAVE_GLOBAL_LIMITS = 'INACTIVE_SAVE_GLOBAL_LIMITS';
const LOADING_SAVE_GLOBAL_LIMITS = 'LOADING_SAVE_GLOBAL_LIMITS';
const SAVE_GLOBAL_LIMITS_SUCCEEDED = 'SAVE_GLOBAL_LIMITS_SUCCEEDED';
const SAVE_GLOBAL_LIMITS_FAILED = 'SAVE_GLOBAL_LIMITS_FAILED';

export {
  INACTIVE_FETCH_GLOBAL_LIMITS, LOADING_FETCH_GLOBAL_LIMITS, FETCH_GLOBAL_LIMITS_SUCCEEDED, FETCH_GLOBAL_LIMITS_FAILED,
  INACTIVE_SAVE_GLOBAL_LIMITS, LOADING_SAVE_GLOBAL_LIMITS, SAVE_GLOBAL_LIMITS_SUCCEEDED, SAVE_GLOBAL_LIMITS_FAILED,
};
