const LOADING_INVITE = 'LOADING_INVITE';
const INVITE_FAILED = 'INVITE_FAILED';
const INVITE_SUCCEEDED = 'INVITE_SUCCEEDED';
const INVITE_INACTIVE = 'INVITE_INACTIVE';

export {
  LOADING_INVITE, INVITE_FAILED, INVITE_SUCCEEDED, INVITE_INACTIVE,
};
