const INACTIVE_FETCH_LEARNING_DAYS = 'INACTIVE_FETCH_LEARNING_DAYS';
const LOADING_FETCH_LEARNING_DAYS = 'LOADING_FETCH_LEARNING_DAYS';
const FETCH_LEARNING_DAYS_SUCCEEDED = 'FETCH_LEARNING_DAYS_SUCCEEDED';
const FETCH_LEARNING_DAYS_FAILED = 'FETCH_LEARNING_DAYS_FAILED';

const INACTIVE_START_LEARNING_DAY = 'INACTIVE_START_LEARNING_DAY';
const LOADING_START_LEARNING_DAY = 'LOADING_START_LEARNING_DAY';
const START_LEARNING_DAY_SUCCEEDED = 'START_LEARNING_DAY_SUCCEEDED';
const START_LEARNING_DAY_FAILED = 'START_LEARNING_DAY_FAILED';

const INACTIVE_CANCEL_LEARNING_DAY = 'INACTIVE_CANCEL_LEARNING_DAY';
const LOADING_CANCEL_LEARNING_DAY = 'LOADING_CANCEL_LEARNING_DAY';
const CANCEL_LEARNING_DAY_SUCCEEDED = 'CANCEL_LEARNING_DAY_SUCCEEDED';
const CANCEL_LEARNING_DAY_FAILED = 'CANCEL_LEARNING_DAY_FAILED';

const INACTIVE_UPDATE_LEARNING_DAY = 'INACTIVE_UPDATE_LEARNING_DAY';
const LOADING_UPDATE_LEARNING_DAY = 'LOADING_UPDATE_LEARNING_DAY';
const UPDATE_LEARNING_DAY_SUCCEEDED = 'UPDATE_LEARNING_DAY_SUCCEEDED';
const UPDATE_LEARNING_DAY_FAILED = 'UPDATE_LEARNING_DAY_FAILED';

export {
  INACTIVE_FETCH_LEARNING_DAYS, LOADING_FETCH_LEARNING_DAYS, FETCH_LEARNING_DAYS_SUCCEEDED, FETCH_LEARNING_DAYS_FAILED,
  LOADING_START_LEARNING_DAY, START_LEARNING_DAY_FAILED, START_LEARNING_DAY_SUCCEEDED,
  INACTIVE_START_LEARNING_DAY, INACTIVE_CANCEL_LEARNING_DAY, LOADING_CANCEL_LEARNING_DAY, CANCEL_LEARNING_DAY_FAILED, CANCEL_LEARNING_DAY_SUCCEEDED,
  INACTIVE_UPDATE_LEARNING_DAY, LOADING_UPDATE_LEARNING_DAY, UPDATE_LEARNING_DAY_FAILED, UPDATE_LEARNING_DAY_SUCCEEDED,
};
