const INACTIVE_FETCH_LEARNING_DAYS = 'INACTIVE_FETCH_LEARNING_DAYS';
const LOADING_FETCH_LEARNING_DAYS = 'LOADING_FETCH_LEARNING_DAYS';
const FETCH_LEARNING_DAYS_SUCCEEDED = 'FETCH_LEARNING_DAYS_SUCCEEDED';
const FETCH_LEARNING_DAYS_FAILED = 'FETCH_LEARNING_DAYS_FAILED';

const LOADING_START_LEARNING_DAY = 'LOADING_START_LEARNING_DAY';
const START_LEARNING_DAY_SUCCEEDED = 'START_LEARNING_DAY_SUCCEEDED';
const START_LEARNING_DAY_FAILED = 'START_LEARNING_DAY_FAILED';

export {
  INACTIVE_FETCH_LEARNING_DAYS, LOADING_FETCH_LEARNING_DAYS, FETCH_LEARNING_DAYS_SUCCEEDED, FETCH_LEARNING_DAYS_FAILED,
  LOADING_START_LEARNING_DAY, START_LEARNING_DAY_FAILED, START_LEARNING_DAY_SUCCEEDED,
};
