const INACTIVE_FETCH_LEARNING_DAYS = 'INACTIVE_FETCH_LEARNING_DAYS';
const LOADING_FETCH_LEARNING_DAYS = 'LOADING_FETCH_LEARNING_DAYS';
const FETCH_LEARNING_DAYS_SUCCEEDED = 'FETCH_LEARNING_DAYS_SUCCEEDED';
const FETCH_LEARNING_DAYS_FAILED = 'FETCH_LEARNING_DAYS_FAILED';

export {
  INACTIVE_FETCH_LEARNING_DAYS, LOADING_FETCH_LEARNING_DAYS, FETCH_LEARNING_DAYS_SUCCEEDED, FETCH_LEARNING_DAYS_FAILED,
};
