const INACTIVE_FETCH_LIMITS = 'INACTIVE_FETCH_LIMITS';
const LOADING_FETCH_LIMITS = 'LOADING_FETCH_LIMITS';
const FETCH_LIMITS_SUCCEEDED = 'FETCH_LIMITS_SUCCEEDED';
const FETCH_LIMITS_FAILED = 'FETCH_LIMITS_FAILED';

export {
  INACTIVE_FETCH_LIMITS, LOADING_FETCH_LIMITS, FETCH_LIMITS_SUCCEEDED, FETCH_LIMITS_FAILED,
};
