const LOADING_MY_SUBORDINATES_TREE = 'LOADING_MY_SUBORDINATES_TREE';
const FETCH_MY_SUBORDINATES_TREE_SUCCEEDED = 'FETCH_MY_SUBORDINATES_TREE_SUCCEEDED';
const FETCH_MY_SUBORDINATES_TREE_FAILED = 'FETCH_MY_SUBORDINATES_TREE_FAILED';

export {
  LOADING_MY_SUBORDINATES_TREE, FETCH_MY_SUBORDINATES_TREE_SUCCEEDED, FETCH_MY_SUBORDINATES_TREE_FAILED,
};
