const LOADING_MY_TEAM = 'LOADING_MY_TEAM';
const FETCH_MY_TEAM_SUCCEEDED = 'FETCH_MY_TEAM_SUCCEEDED';
const FETCH_MY_TEAM_FAILED = 'FETCH_MY_TEAM_FAILED';

export {
  LOADING_MY_TEAM, FETCH_MY_TEAM_SUCCEEDED, FETCH_MY_TEAM_FAILED,
};
