const LOADING_MY_TEAM_TREE = 'LOADING_MY_TEAM_TREE';
const FETCH_MY_TEAM_TREE_SUCCEEDED = 'FETCH_MY_TEAM_TREE_SUCCEEDED';
const FETCH_MY_TEAM_TREE_FAILED = 'FETCH_MY_TEAM_TREE_FAILED';

export {
  LOADING_MY_TEAM_TREE, FETCH_MY_TEAM_TREE_SUCCEEDED, FETCH_MY_TEAM_TREE_FAILED,
};
