const LOADING_PERSONAL_GOALS = 'LOADING_PERSONAL_GOALS';
const FETCH_PERSONAL_GOALS_SUCCEEDED = 'FETCH_PERSONAL_GOALS_SUCCEEDED';
const FETCH_PERSONAL_GOALS_FAILED = 'FETCH_PERSONAL_GOALS_FAILED';

export {
  LOADING_PERSONAL_GOALS, FETCH_PERSONAL_GOALS_SUCCEEDED, FETCH_PERSONAL_GOALS_FAILED,
};
