const LOADING_PERSONAL_TREE = 'LOADING_PERSONAL_TREE';
const FETCH_PERSONAL_TREE_SUCCEEDED = 'FETCH_PERSONAL_TREE_SUCCEEDED';
const FETCH_PERSONAL_TREE_FAILED = 'FETCH_PERSONAL_TREE_FAILED';

export {
  LOADING_PERSONAL_TREE, FETCH_PERSONAL_TREE_SUCCEEDED, FETCH_PERSONAL_TREE_FAILED,
};
