const LOADING_PERSONAL_GOALS = 'LOADING_PERSONAL_GOALS';
const FETCH_PERSONAL_GOALS_SUCCEEDED = 'FETCH_PERSONAL_GOALS_SUCCEEDED';
const FETCH_PERSONAL_GOALS_FAILED = 'FETCH_PERSONAL_GOALS_FAILED';

const INACTIVE_ADD_SELF_PERSONAL_GOAL = 'INACTIVE_ADD_SELF_PERSONAL_GOAL';
const LOADING_ADD_SELF_PERSONAL_GOAL = 'LOADING_ADD_SELF_PERSONAL_GOAL';
const ADD_SELF_PERSONAL_GOAL_SUCCEEDED = 'ADD_SELF_PERSONAL_GOAL_SUCCEEDED';
const ADD_SELF_PERSONAL_GOAL_FAILED = 'ADD_SELF_PERSONAL_GOAL_FAILED';

export {
  LOADING_PERSONAL_GOALS, FETCH_PERSONAL_GOALS_SUCCEEDED, FETCH_PERSONAL_GOALS_FAILED,
  LOADING_ADD_SELF_PERSONAL_GOAL, ADD_SELF_PERSONAL_GOAL_FAILED, ADD_SELF_PERSONAL_GOAL_SUCCEEDED,
  INACTIVE_ADD_SELF_PERSONAL_GOAL,
};
