const LOADING_VALIDATE_INVITEID = 'LOADING_VALIDATE_INVITEID';
const VALIDATE_INVITEID_SUCCEEDED = 'VALIDATE_INVITEID_SUCCEEDED';
const VALIDATE_INVITEID_FAILED = 'VALIDATE_INVITEID_FAILED';

const LOADING_REGISTER = 'LOADING_REGISTER';
const REGISTER_FAILED = 'REGISTER_FAILED';
const REGISTER_SUCCEEDED = 'REGISTER_SUCCEEDED';

export {
  LOADING_REGISTER, REGISTER_FAILED, REGISTER_SUCCEEDED, LOADING_VALIDATE_INVITEID, VALIDATE_INVITEID_SUCCEEDED, VALIDATE_INVITEID_FAILED,
};
