const LOADING_SINGLE_SUBORDINATE_TREE = 'LOADING_SINGLE_SUBORDINATE_TREE';
const FETCH_SINGLE_SUBORDINATE_TREE_SUCCEEDED = 'FETCH_SINGLE_SUBORDINATE_TREE_SUCCEEDED';
const FETCH_SINGLE_SUBORDINATE_TREE_FAILED = 'FETCH_SINGLE_SUBORDINATE_TREE_FAILED';

export {
  LOADING_SINGLE_SUBORDINATE_TREE, FETCH_SINGLE_SUBORDINATE_TREE_SUCCEEDED, FETCH_SINGLE_SUBORDINATE_TREE_FAILED,
};
