const LOADING_SINGLE_TEAM_TREE = 'LOADING_SINGLE_TEAM_TREE';
const FETCH_SINGLE_TEAM_TREE_SUCCEEDED = 'FETCH_SINGLE_TEAM_TREE_SUCCEEDED';
const FETCH_SINGLE_TEAM_TREE_FAILED = 'FETCH_SINGLE_TEAM_TREE_FAILED';

export {
  LOADING_SINGLE_TEAM_TREE, FETCH_SINGLE_TEAM_TREE_SUCCEEDED, FETCH_SINGLE_TEAM_TREE_FAILED,
};
