const MODAL_MAX_HEIGHT = '800px';
const PAGE_HEIGHT = '1000px';
const TOPICS_TREE_HEIGHT = 500;
const TOPICS_TREE_WIDTH = 1000;
const INPUTAREA_MIN_HEIGHT = '120px';

export {
  MODAL_MAX_HEIGHT, PAGE_HEIGHT, TOPICS_TREE_HEIGHT, TOPICS_TREE_WIDTH, INPUTAREA_MIN_HEIGHT,
};
