const MODAL_MAX_HEIGHT = '800px';
const PAGE_HEIGHT = '1140px';

const TOPICS_TREE_HEIGHT = 650;
const TOPICS_TREE_WIDTH = 1200;

const INPUTAREA_MIN_HEIGHT = '120px';

const FONT_FAMILY = 'Arial';

const TREE_CONTAINER_FILL = '#272b4d';
const TREE_NODE_FILL = '#272b4d';
const TREE_CHILDREN_NODE_FILL = '#03c0dc';
const TREE_NOT_CHILDREN_NODE_FILL = '#26deb0';
const TREE_STROKE_COLOR = '#374469';

export {
  MODAL_MAX_HEIGHT,
  PAGE_HEIGHT,
  TOPICS_TREE_HEIGHT,
  TOPICS_TREE_WIDTH,
  INPUTAREA_MIN_HEIGHT,
  TREE_CONTAINER_FILL,
  TREE_CHILDREN_NODE_FILL,
  TREE_NOT_CHILDREN_NODE_FILL,
  TREE_NODE_FILL,
  FONT_FAMILY,
  TREE_STROKE_COLOR,
};
