const LOADING_SUBORDINATES = 'LOADING_SUBORDINATES';
const FETCH_SUBORDINATES_SUCCEEDED = 'FETCH_SUBORDINATES_SUCCEEDED';
const FETCH_SUBORDINATES_FAILED = 'FETCH_SUBORDINATES_FAILED';

const INACTIVE_UPDATE_SUBORDINATE = 'INACTIVE_UPDATE_SUBORDINATE';
const LOADING_UPDATE_SUBORDINATE = 'LOADING_UPDATE_SUBORDINATE';
const UPDATE_SUBORDINATE_SUCCEEDED = 'UPDATE_SUBORDINATE_SUCCEEDED';
const UPDATE_SUBORDINATE_FAILED = 'UPDATE_SUBORDINATE_FAILED';

const INACTIVE_DELETE_SUBORDINATE = 'INACTIVE_DELETE_SUBORDINATE';
const LOADING_DELETE_SUBORDINATE = 'LOADING_DELETE_SUBORDINATE';
const DELETE_SUBORDINATE_SUCCEEDED = 'DELETE_SUBORDINATE_SUCCEEDED';
const DELETE_SUBORDINATE_DAY_FAILED = 'DELETE_SUBORDINATE_DAY_FAILED';

export {
  LOADING_SUBORDINATES, FETCH_SUBORDINATES_SUCCEEDED, FETCH_SUBORDINATES_FAILED,
  INACTIVE_UPDATE_SUBORDINATE, LOADING_UPDATE_SUBORDINATE, UPDATE_SUBORDINATE_SUCCEEDED, UPDATE_SUBORDINATE_FAILED,
  INACTIVE_DELETE_SUBORDINATE, LOADING_DELETE_SUBORDINATE, DELETE_SUBORDINATE_SUCCEEDED, DELETE_SUBORDINATE_DAY_FAILED,
};
