const LOADING_SUBORDINATES = 'LOADING_SUBORDINATES';
const FETCH_SUBORDINATES_SUCCEEDED = 'FETCH_SUBORDINATES_SUCCEEDED';
const FETCH_SUBORDINATES_FAILED = 'FETCH_SUBORDINATES_FAILED';

export {
  LOADING_SUBORDINATES, FETCH_SUBORDINATES_SUCCEEDED, FETCH_SUBORDINATES_FAILED,
};
