const HIDDEN_SUCCESS_TOAST = 'HIDDEN_SUCCESS_TOAST';
const VISIBLE_SUCCESS_TOAST = 'VISIBLE_SUCCESS_TOAST';

const HIDDEN_ERROR_TOAST = 'HIDDEN_ERROR_TOAST';
const VISIBLE_ERROR_TOAST = 'VISIBLE_ERROR_TOAST';

export {
  HIDDEN_ERROR_TOAST, HIDDEN_SUCCESS_TOAST, VISIBLE_SUCCESS_TOAST, VISIBLE_ERROR_TOAST,
};
