const LOADING_CREATE_TOPIC = 'LOADING_CREATE_TOPIC';
const CREATE_TOPIC_FAILED = 'CREATE_TOPIC_FAILED';
const CREATE_TOPIC_SUCCEEDED = 'CREATE_TOPIC_SUCCEEDED';
const CREATE_TOPIC_INACTIVE = 'CREATE_TOPIC_INACTIVE';

export {
  LOADING_CREATE_TOPIC, CREATE_TOPIC_FAILED, CREATE_TOPIC_SUCCEEDED, CREATE_TOPIC_INACTIVE,
};
