const LOADING_TOPICS_TREE = 'LOADING_TOPICS_TREE';
const FETCH_TOPICS_TREE_FAILED = 'FETCH_TOPICS_TREE_FAILED';
const FETCH_TOPICS_TREE_SUCCEEDED = 'FETCH_TOPICS_TREE_SUCCEEDED';

export {
  LOADING_TOPICS_TREE, FETCH_TOPICS_TREE_FAILED, FETCH_TOPICS_TREE_SUCCEEDED,
};
