const LOADING_CREATE_TOPIC = 'LOADING_CREATE_TOPIC';
const CREATE_TOPIC_FAILED = 'CREATE_TOPIC_FAILED';
const CREATE_TOPIC_SUCCEEDED = 'CREATE_TOPIC_SUCCEEDED';
const CREATE_TOPIC_INACTIVE = 'CREATE_TOPIC_INACTIVE';

const LOADING_FETCH_TOPIC = 'LOADING_FETCH_TOPIC';
const FETCH_TOPIC_FAILED = 'FETCH_TOPIC_FAILED';
const FETCH_TOPIC_SUCCEEDED = 'FETCH_TOPIC_SUCCEEDED';

export {
  LOADING_CREATE_TOPIC, CREATE_TOPIC_FAILED, CREATE_TOPIC_SUCCEEDED, CREATE_TOPIC_INACTIVE, LOADING_FETCH_TOPIC, FETCH_TOPIC_FAILED, FETCH_TOPIC_SUCCEEDED,
};
