const LOADING_CREATE_TOPIC = 'LOADING_CREATE_TOPIC';
const CREATE_TOPIC_FAILED = 'CREATE_TOPIC_FAILED';
const CREATE_TOPIC_SUCCEEDED = 'CREATE_TOPIC_SUCCEEDED';
const CREATE_TOPIC_INACTIVE = 'CREATE_TOPIC_INACTIVE';

const LOADING_FETCH_TOPIC = 'LOADING_FETCH_TOPIC';
const FETCH_TOPIC_FAILED = 'FETCH_TOPIC_FAILED';
const FETCH_TOPIC_SUCCEEDED = 'FETCH_TOPIC_SUCCEEDED';

const LOADING_FETCH_LEARNED_TOPICS = 'LOADING_FETCHED_LEARNED_TOPICS';
const FETCH_LEARNED_TOPICS_FAILED = 'FETCH_LEARNED_TOPICS_FAILED';
const FETCH_LEARNED_TOPICS_SUCCEEDED = 'FETCH_LEARNED_TOPICS_SUCCEEDED';
const FETCH_LEARNED_TOPICS_INACTIVE = 'FETCH_LEARNED_TOPICS_INACTIVE';

export {
  LOADING_CREATE_TOPIC, CREATE_TOPIC_FAILED, CREATE_TOPIC_SUCCEEDED, CREATE_TOPIC_INACTIVE, LOADING_FETCH_TOPIC, FETCH_TOPIC_FAILED, FETCH_TOPIC_SUCCEEDED,
  LOADING_FETCH_LEARNED_TOPICS, FETCH_LEARNED_TOPICS_FAILED, FETCH_LEARNED_TOPICS_SUCCEEDED, FETCH_LEARNED_TOPICS_INACTIVE,
};
